---
- name: template the first_rules.yml file
  template:
    src: first_rules.yml.j2
    dest: "/home/{{ ansible_user }}/rules/first_rules.yml"
    mode: 0775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    seuser: system_u
    setype: container_file_t


- name: copy custom rules
  copy: 
    src: "{{ custom_rules_file }}"
    dest: "/home/{{ ansible_user }}/rules/custom_rules.yml"
    mode: 0775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    seuser: system_u
    setype: container_file_t
  when: custom_rules_file is defined

- name: reload prometheus config
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
